--liquibase formatted sql

--changeset bhfreiberger:29032021210000
CREATE TABLE PROCEDIMENTO_MEDICO (
	ID INT NOT NULL AUTO_INCREMENT,
    COD_PROC INT NOT NULL,
    AGE INT NOT NULL,
	SEX VARCHAR(1) NOT NULL,
    ALLOWED BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (ID) 
);